version: "3.6"
services:
  app:
    build: .
    ports:
      - 8080:8080
    env_file: .env
    depends_on:
      - db
  db:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
